name: Publish Github Pages
on:
  push:
    branches:
      - 'main'

jobs:
  publish-demo:
    name: Publish to Github Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm ci
    - run: npm run build
    - name: Cleanup and prepare pages
      run: |
        rm -rf ./gh-pages-staging
        mkdir -p ./gh-pages-staging/main/
        cp ./dist/* ./gh-pages-staging/main/
        cp ./static/* ./gh-pages-staging/main/
    - name: Deploy gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages-staging/main
        destination_dir: ./main
